### ISSUE TITLE
MQTT plugs stopped working after version 1.2.9

### ISSUE THREAD

**Issue by mlebaugh** [cbpowell/SenseLink#19]
I was upgrading from 1.2.9 to the latest today and it seems I'm unable to due to some issue with the Mqtt plugs. I reverted back to the previous version I was using. 

Below is the log from the error. 

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 1029, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/usr/local/lib/python3.10/site-packages/senselink/senselink.py", line 93, in datagram_received
    response = inst.generate_response()
  File "/usr/local/lib/python3.10/site-packages/senselink/plug_instance.py", line 113, in generate_response
    power = self.data_source.power
  File "/usr/local/lib/python3.10/site-packages/senselink/data_source.py", line 91, in power
    plug_powers = list(map(lambda plug: plug.power, self.elements))
  File "/usr/local/lib/python3.10/site-packages/senselink/data_source.py", line 91, in <lambda>
    plug_powers = list(map(lambda plug: plug.power, self.elements))
  File "/usr/local/lib/python3.10/site-packages/senselink/plug_instance.py", line 109, in power
    return self.data_source.get_power()
AttributeError: 'MQTTSource' object has no attribute 'get_power'
DEBUG:root:Power topic update for Dryer1: 2

**Comment by cbpowell** [comment]
Thanks for the heads up, I’ll check it out! Clearly I need to improve my testing…

**Comment by cbpowell** [comment]
Found it - was using the incorrect power property for aggregate type plugs. Thanks again!

**Comment by mlebaugh** [comment]
Apologies for the delay. I just tried to update again and the issue is still persisting on the latest version, same error as before.

**Comment by cbpowell** [comment]
No worries! Hmm could you post an error log again? At least if it's not the exact same as above. That would help me narrow it down.

Also I forget, do you run it in Docker or directly?

**Comment by mlebaugh** [comment]
I take that back, it is working on the latest. however I'm still seeing this frequently in the logs.

ERROR:asyncio:Exception in callback _SelectorDatagramTransport._read_ready()
handle: <Handle _SelectorDatagramTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 1026, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/usr/local/lib/python3.10/site-packages/senselink/senselink.py", line 93, in datagram_received
    response = inst.generate_response()
  File "/usr/local/lib/python3.10/site-packages/senselink/plug_instance.py", line 113, in generate_response
    power = self.data_source.power
  File "/usr/local/lib/python3.10/site-packages/senselink/data_source.py", line 91, in power
    plug_powers = list(map(lambda plug: plug.power, self.elements))
  File "/usr/local/lib/python3.10/site-packages/senselink/data_source.py", line 91, in <lambda>
    plug_powers = list(map(lambda plug: plug.power, self.elements))
  File "/usr/local/lib/python3.10/site-packages/senselink/plug_instance.py", line 109, in power
    return self.data_source.get_power()
AttributeError: 'MQTTSource' object has no attribute 'get_power'

Running via docker.

**Comment by cbpowell** [comment]
So complete facepalm on my part, I was getting all fancy with automated Github Actions Docker image builds and PyPi packages, and made a silly mistake. The Dockerfile specified to simply pull the latest package via pip, but of course if the pip package isn't updated _before_ the Docker image gets built…you get the prior version.

The 2.0.3 version now released should fix that, and builds the Docker image locally rather than pulling via pip.

**Comment by mlebaugh** [comment]
Looks good now.

Thanks again!

**Comment by cbpowell** [comment]
Awesome, thank you for the help fixing it!
